### ISSUE TITLE
> Have a second worksheet in each spreadsheet file that contains some options for the generated page...

### ISSUE THREAD

**Issue by Nichebiche** [gnosischain/validator-data-generator#13]
> Have a second worksheet in each spreadsheet file that contains some options for the generated page...

| Header | Header | Header | Header | Header |
|--------|--------|--------|--------|--------|
| Cell | Cell

_Originally posted by @123123nope in https://github.com/coinbase/commerce-onchain-payment-protocol/issues/15_

**Comment by Goop-arsh** [comment]
[]()

**Comment by Goop-arsh** [comment]
T
